language: node_js
node_js:
  - 'node'
  - '10.14'
install:
  - yarn global add @commitlint/travis-cli coveralls
  - yarn
script:
  - 'commitlint-travis && yarn test --coverage && coveralls < coverage/lcov.info'
cache: yarn
