language: node_js
node_js:
  - 'node'
  - '10.14'
install:
  - npm install -g @commitlint/travis-cli coveralls
  - npm install
script:
  - 'commitlint-travis && npm test -- --coverage && coveralls < coverage/lcov.info'
cache: npm
