FORMAT: 1A9
HOST: https://www.v2ex.com/api

# V2EX 非官方 API 列表 1.0.0

V2EX 非官方 API 列表，仅供参考，欢迎补充。

接口来源：https://github.com/djyde/V2EX-API

# Site [/site]

网站相关接口

## 获取网站信息 [GET /site/info.json]

+ Response 200 (application/json)

    + Attributes
        + title: V2EX - 站名
        + slogan: way to explore - 口号
        + `description`: 创意工作者们的社区 - 网站描述
        + domain: www.v2ex.com - 网站域名

## 获取网站状态 [GET /site/stats.json]

+ Response 200 (application/json)

    + Attributes
        + `topic_max`: 625508 (number) - 主题数量
        + `member_max`: 457101 (number) - 用户数量

## 获取 Livid 个人资料 [GET /site/livid.json]

这是一个不存在的接口，用来测试 404。

+ Response 404 (application/json)

# Node [/nodes]

节点相关接口

## 获取所有节点列表 [GET /nodes/all.json]

+ Response 200 (application/json)

    + Attributes (array)
        + (object)
            + `avatar_large`: `//cdn.v2ex.com/navatar/c4ca/4238/1_large.png?m=1494924246`
            + name: babel - 节点名称
            + `avatar_normal`: `//cdn.v2ex.com/navatar/c4ca/4238/1_normal.png?m=1494924246`
            + title: Project Babel
            + url: `https://www.v2ex.com/go/babel`
            + topics: 1122 (number)
            + footer: `V2EX 基于 Project Babel 驱动。Project Babel 是用 Python 语言写成的，运行于 Google App Engine 云计算平台上的社区软件。Project Babel 当前开发分支 2.5。最新版本可以从 <a href="http://github.com/livid/v2ex" target="_blank">GitHub</a> 获取。`
            + header: `Project Babel - 帮助你在云平台上搭建自己的社区`
            + `title_alternative`: Project Babel
            + `avatar_mini`: `//cdn.v2ex.com/navatar/c4ca/4238/1_mini.png?m=1494924246`
            + stars: 392 (number)
            + root: false (boolean)
            + id: 1 (number)
            + `parent_node_name`: v2ex
        + (object)
            + `avatar_large`: `//cdn.v2ex.com/navatar/c81e/728d/2_large.png?m=1497247332`
            + name: v2ex
            + `avatar_normal`: `//cdn.v2ex.com/navatar/c81e/728d/2_normal.png?m=1497247332`
            + title: V2EX
            + url: `https://www.v2ex.com/go/v2ex`
            + topics: 3330 (number)
            + footer
            + header: 这里讨论和发布关于 V2EX 站点的发展。
            + `title_alternative`: V2EX
            + `avatar_mini`: `//cdn.v2ex.com/navatar/c81e/728d/2_mini.png?m=1497247332`
            + stars: 1052 (number)
            + root: true (boolean)
            + id: 2 (number)
            + `parent_node_name`: v2ex

## 获取指定节点信息 [GET /nodes/show.json{?id,name}]

节点 ID 和节点名两个参数二选一。

+ Parameters
    + id: `2` (number) - 节点 ID

+ Response 200 (application/json)

    + Attributes
        + `avatar_large`: `//cdn.v2ex.com/navatar/c81e/728d/2_large.png?m=1497247332`
        + name: v2ex
        + `avatar_normal`: `//cdn.v2ex.com/navatar/c81e/728d/2_normal.png?m=1497247332`
        + title: V2EX
        + url: `https://www.v2ex.com/go/v2ex`
        + topics: 3330 (number)
        + footer
        + header: 这里讨论和发布关于 V2EX 站点的发展。
        + `title_alternative`: V2EX
        + `avatar_mini`: `//cdn.v2ex.com/navatar/c81e/728d/2_mini.png?m=1497247332`
        + stars: 1052 (number)
        + root: true (boolean)
        + id: 2 (number)
        + `parent_node_name`: v2ex

+ Request (application/json)

    + Parameters
        + name: `stackia` - 节点名

+ Response 200 (application/json)

    + Attributes
        + status: error
        + message: Object Not Found
        + `rate_limit` - API 访问次数限制相关信息
            + used: 3 (number)
            + `hourly_quota`: 120 (number)
            + `hourly_remaining`: 117 (number)

# Topic [/topics]

主题相关接口

## 获取最新主题列表 [GET /topics/latest.json]

+ Response 200 (application/json)

    + Attributes (array)
        + (object)
            + node
                + `avatar_large`: `//cdn.v2ex.com/navatar/c20a/d4d7/12_large.png?m=1575345595`
                + name: qna
                + `avatar_normal`: `//cdn.v2ex.com/navatar/c20a/d4d7/12_normal.png?m=1575345595`
                + title: 问与答
                + url: `https://www.v2ex.com/go/qna`
                + topics: 144222 (number)
                + footer
                + header: 一个更好的世界需要你持续地提出好问题。
                + `title_alternative`: Questions and Answers
                + `avatar_mini`: `//cdn.v2ex.com/navatar/c20a/d4d7/12_mini.png?m=1575345595`
                + stars: 2727 (number)
                + root: false (boolean)
                + id: 12 (number)
                + `parent_node_name`: v2ex
            + `member` - 发帖人信息
                + username: Illyasvielvon
                + website (object, nullable)
                + github (object, nullable)
                + psn (object, nullable)
                + `avatar_normal`: `//cdn.v2ex.com/avatar/681e/eda4/454554_mini.png?m=1575356274`
                + bio (object, nullable)
                + url: `https://www.v2ex.com/u/Illyasvielvon`
                + tagline (object, nullable)
                + twitter (object, nullable)
                + created: 1574313664 (number)
                + `avatar_large`: `//cdn.v2ex.com/avatar/681e/eda4/454554_mini.png?m=1575356274`
                + `avatar_mini`: `//cdn.v2ex.com/avatar/681e/eda4/454554_mini.png?m=1575356274`
                + location (object, nullable)
                + btc (object, nullable)
                + id: 454554 (number)
            + `last_reply_by`
            + `last_touched`: 1575342161 (number)
            + title: 想问一下，以后想从事 动漫 游戏 这种公司的程序员工作 要点什么技能点。。
            + url: `https://www.v2ex.com/t/625514`
            + created: 1575356561 (number)
            + content: `今年刚本科毕业。。python c++用的多，现在刚开始 ROS 机器人 还有计算机视觉的一些模型开发。 ...`
            + `content_rendered`: `今年刚本科毕业。。python c++用的多，现在刚开始 ROS 机器人 还有计算机视觉的一些模型开发。<br /><br />想为以后考虑以下，想进那种公司的现在开始 c++服务器端 分布式方面？`
            + `last_modified`: 1575356561 (number)
            + replies: 0 (number)
            + id: 625514 (number)

## 获取热门主题列表 [GET /topics/hot.json]

+ Response 200 (application/json)

    + Attributes (array)
        + (object)
            + node
                + `avatar_large`: `/static/img/node_large.png`
                + name: eggpain
                + `avatar_normal`: `/static/img/node_normal.png`
                + title: 强迫症
                + url: `https://www.v2ex.com/go/eggpain`
                + topics: 63 (number)
                + footer
                + header
                + `title_alternative`: Egg Pain
                + `avatar_mini`: `/static/img/node_mini.png`
                + stars: 25 (number)
                + root: false (boolean)
                + id: 157 (number)
                + `parent_node_name`
            + `member`
                + username: dengbt
                + website
                + github
                + psn
                + `avatar_normal`: `//cdn.v2ex.com/avatar/f9ba/1f50/330562_mini.png?m=1574992209`
                + bio: Boy.
                + url: `https://www.v2ex.com/u/dengbt`
                + tagline
                + twitter
                + created: 1532152966 (number)
                + `avatar_large`: `//cdn.v2ex.com/avatar/f9ba/1f50/330562_mini.png?m=1574992209`
                + `avatar_mini`: `//cdn.v2ex.com/avatar/f9ba/1f50/330562_mini.png?m=1574992209`
                + location: bhh
                + btc
                + id: 330562 (number)
            + `last_reply_by`: djs
            + `last_touched`: 1575356505 (number)
            + title: 如何劝动老婆不要买 iPhone
            + url: `https://www.v2ex.com/t/625138`
            + created: 1575274366 (number)
            + content: # 用途： ...
            + `content_rendered`: `<h1>用途：</h1> ...`
            + `last_modified`: 1575274366 (number)
            + replies: 259 (number)
            + id: 625138 (number)

## 获取指定主题信息 [GET /topics/show.json{?id,username,node_id,node_name}]

参数四选一。

+ Parameters
    + id: `1000` (number)

+ Response 200 (application/json)

    + Attributes (array)
        + (object)
            + node
                + `avatar_large`: `//cdn.v2ex.com/navatar/c4ca/4238/1_large.png?m=1494924246`
                + name: babel
                + `avatar_normal`: `//cdn.v2ex.com/navatar/c4ca/4238/1_normal.png?m=1494924246`
                + title: Project Babel
                + url: `https://www.v2ex.com/go/babel`
                + topics: 1122 (number)
                + footer: `V2EX 基于 Project Babel 驱动。Project Babel 是用 Python 语言写成的，运行于 Google App Engine 云计算平台上的社区软件。Project Babel 当前开发分支 2.5。最新版本可以从 <a href="http://github.com/livid/v2ex" target="_blank">GitHub</a> 获取。`
                + header: `Project Babel - 帮助你在云平台上搭建自己的社区`
                + `title_alternative`: Project Babel
                + `avatar_mini`: `//cdn.v2ex.com/navatar/c4ca/4238/1_mini.png?m=1494924246`
                + stars: 392 (number)
                + root: false (boolean)
                + id: 1 (number)
                + `parent_node_name`: v2ex
            + `member`
                + username: Livid
                + website: `https://livid.v2ex.com/`
                + github
                + psn
                + `avatar_normal`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1553581155`
                + bio: Remember the bigger green
                + url: `https://www.v2ex.com/u/Livid`
                + tagline: Gravitated and spellbound
                + twitter
                + created: 1272203146 (number)
                + `avatar_large`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1553581155`
                + `avatar_mini`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1553581155`
                + location
                + btc
                + id: 1 (number)
            + `last_reply_by`: dimlau
            + `last_touched`: 1280285385 (number)
            + title: Google App Engine x MobileMe
            + url: `https://www.v2ex.com/t/1000`
            + created: 1280192329 (number) - 主题创建时间戳
            + content: 从现在开始，新上传到 V2EX 的头像将存储在 MobileMe iDisk 中。这是 V2EX 到目前为之所用到的第三个云。 ...
            + `content_rendered`: 从现在开始，新上传到 V2EX 的头像将存储在 MobileMe iDisk 中。这是 V2EX 到目前为之所用到的第三个云。 ...
            + `last_modified`: 1335004238 (number)
            + replies: 14 (number)
            + id: 1000 (number)

+ Request (application/json)

    + Parameters
        + username: `Livid` - 根据用户名取该用户所发表主题
        + node_id (object) - 根据节点 ID 取该节点下所有主题
        + node_name (object) - 根据节点名取该节点下所有主题

+ Response 200 (application/json)

    + Attributes (array)
        + (object)
            + node
                + `avatar_large`: `//cdn.v2ex.com/navatar/a3c6/5c29/108_large.png?m=1574910160`
                + name: bb
                + `avatar_normal`: `//cdn.v2ex.com/navatar/a3c6/5c29/108_normal.png?m=1574910160`
                + title: 宽带症候群
                + url: `https://www.v2ex.com/go/bb`
                + topics: 6872 (number)
                + footer
                + header: 网速很重要。比快更快。
                + `title_alternative`: Broadband Symptom Complex
                + `avatar_mini`: `//cdn.v2ex.com/navatar/a3c6/5c29/108_mini.png?m=1574910160`
                + stars: 3827 (number)
                + root: false (boolean)
                + id: 108 (number)
                + `parent_node_name`: geek
            + `member`
                + username: Livid
                + website: `https://livid.v2ex.com/`
                + github
                + psn
                + `avatar_normal`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1553581155`
                + bio: Remember the bigger green
                + url: `https://www.v2ex.com/u/Livid`
                + tagline: Gravitated and spellbound
                + twitter
                + created: 1272203146 (number)
                + `avatar_large`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1553581155`
                + `avatar_mini`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1553581155`
                + location
                + btc
                + id: 1 (number)
            + `last_reply_by`: abbottcn
            + `last_touched`: 1574565559 (number)
            + title: Slack 开源了他们的 overlay network 工具 Nebula
            + url: `https://www.v2ex.com/t/621442`
            + created: 1574238319 (number)
            + content: `https://github.com/slackhq/nebula ...`
            + `content_rendered`: `<a target="_blank" href="https://github.com/slackhq/nebula" rel="nofollow">https://github.com/slackhq/nebula</a><br /><br />简单来说，就是可以用很简单的方式让全球各地的机器用安全的方式在同一个内网里。`
            + `last_modified`: 1574238332 (number)
            + replies: 59 (number)
            + id: 621442 (number)

# Replies [/replies]

主题回复相关接口

## 获取指定主题的所有回复列表 [GET /replies/show.json{?topic_id,page,page_size}]

+ Parameters
    + topic_id: `1` (number)
    + page: `1` (number) - 当前页数
    + page_size: `20` (number) - 每页条数

+ Response 200 (application/json)

    + Attributes (array)
        + (object)
            + `member`
                + username: Jay
                + website: `http://theboldapp.com`
                + github: yuanhao
                + psn
                + `avatar_normal`: `//cdn.v2ex.com/avatar/a87f/f679/4_mini.png?m=1424948183`
                + bio
                + url: `https://www.v2ex.com/u/Jay`
                + tagline: Engineer. Make things.
                + twitter: yuanhao
                + created: 1272207173 (number)
                + `avatar_large`: `//cdn.v2ex.com/avatar/a87f/f679/4_mini.png?m=1424948183`
                + `avatar_mini`: `//cdn.v2ex.com/avatar/a87f/f679/4_mini.png?m=1424948183`
                + location: Stuttgart
                + btc
                + id: 4 (number)
            + created: 1272207477 (number)
            + `topic_id`: 1 (number)
            + content: 很高兴看到 v2ex 又回来了，等了你半天发第一贴了，憋死我了。 ...
            + `content_rendered`: `很高兴看到 v2ex 又回来了，等了你半天发第一贴了，憋死我了。<br /><br />nice work~`
            + `last_modified`: 1335092176 (number) - 最后编辑时间戳
            + `member_id`: 4 (number)
            + id: 1 (number)

# Members [/members]

用户相关接口

## 获取指定主题的所有回复列表 [GET /members/show.json{?username}]

+ Parameters
    + username: `Livid`

+ Response 200 (application/json)

    + Attributes
        + username: Livid
        + website: `https://livid.v2ex.com/`
        + github
        + psn
        + `avatar_normal`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1553581155` - 头像 URL
        + bio: Remember the bigger green
        + url: `https://www.v2ex.com/u/Livid`
        + tagline: Gravitated and spellbound
        + twitter
        + created: 1272203146 (number)
        + status: found
        + `avatar_large`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1553581155`
        + `avatar_mini`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1553581155`
        + location
        + btc
        + id: 1 (number)

