FORMAT: 1A9
HOST: https://www.v2ex.com/api

# V2EX 非官方 API 列表 1.0.0

V2EX 非官方 API 列表，仅供参考，欢迎补充。

接口来源：https://github.com/djyde/V2EX-API

# Site [/site]

网站相关接口

## 获取网站信息 [GET /site/info.json]

+ Response 200 (application/json)

    + Attributes
        + title: V2EX - 站名
        + slogan: way to explore - 口号
        + `description`: 创意工作者们的社区 - 网站描述
        + domain: www.v2ex.com - 网站域名

## 获取网站状态 [GET /site/stats.json]

+ Response 200 (application/json)

    + Attributes
        + `topic_max`: 653357 (number) - 主题数量
        + `member_max`: 477016 (number) - 用户数量

## 获取 Livid 个人资料 [GET /site/livid.json]

这是一个不存在的接口，用来测试 404。

+ Response 404 (application/json)

# Node [/nodes]

节点相关接口

## 获取所有节点列表 [GET /nodes/all.json]

+ Response 200 (application/json)

    + Attributes (array)
        + (object)
            + `avatar_large`: `//cdn.v2ex.com/navatar/c4ca/4238/1_large.png?m=1494924246`
            + name: babel - 节点名称
            + `avatar_normal`: `//cdn.v2ex.com/navatar/c4ca/4238/1_normal.png?m=1494924246`
            + title: Project Babel
            + url: `https://www.v2ex.com/go/babel`
            + topics: 1122 (number)
            + footer: `V2EX 基于 Project Babel 驱动。Project Babel 是用 Python 语言写成的，运行于 Google App Engine 云计算平台上的社区软件。Project Babel 当前开发分支 2.5。最新版本可以从 <a href="http://github.com/livid/v2ex" target="_blank">GitHub</a> 获取。`
            + header: `Project Babel - 帮助你在云平台上搭建自己的社区`
            + `title_alternative`: Project Babel
            + `avatar_mini`: `//cdn.v2ex.com/navatar/c4ca/4238/1_mini.png?m=1494924246`
            + stars: 397 (number)
            + aliases (array)
            + root: false (boolean)
            + id: 1 (number)
            + `parent_node_name`: v2ex
        + (object)
            + `avatar_large`: `//cdn.v2ex.com/navatar/c81e/728d/2_large.png?m=1497247332`
            + name: v2ex
            + `avatar_normal`: `//cdn.v2ex.com/navatar/c81e/728d/2_normal.png?m=1497247332`
            + title: V2EX
            + url: `https://www.v2ex.com/go/v2ex`
            + topics: 3355 (number)
            + footer
            + header: 这里讨论和发布关于 V2EX 站点的发展。
            + `title_alternative`: V2EX
            + `avatar_mini`: `//cdn.v2ex.com/navatar/c81e/728d/2_mini.png?m=1497247332`
            + stars: 1085 (number)
            + aliases (array)
            + root: true (boolean)
            + id: 2 (number)
            + `parent_node_name`: v2ex

## 获取指定节点信息 [GET /nodes/show.json{?id,name}]

节点 ID 和节点名两个参数二选一。

+ Parameters
    + id: `2` (number) - 节点 ID

+ Response 200 (application/json)

    + Attributes
        + `avatar_large`: `//cdn.v2ex.com/navatar/c81e/728d/2_large.png?m=1497247332`
        + name: v2ex
        + `avatar_normal`: `//cdn.v2ex.com/navatar/c81e/728d/2_normal.png?m=1497247332`
        + title: V2EX
        + url: `https://www.v2ex.com/go/v2ex`
        + topics: 3355 (number)
        + footer
        + header: 这里讨论和发布关于 V2EX 站点的发展。
        + `title_alternative`: V2EX
        + `avatar_mini`: `//cdn.v2ex.com/navatar/c81e/728d/2_mini.png?m=1497247332`
        + stars: 1085 (number)
        + aliases (array)
        + root: true (boolean)
        + id: 2 (number)
        + `parent_node_name`: v2ex

+ Request (application/json)

    + Parameters
        + name: `stackia` - 节点名

+ Response 200 (application/json)

    + Attributes
        + status: error
        + message: Object Not Found
        + `rate_limit` - API 访问次数限制相关信息
            + used: 3 (number)
            + `hourly_quota`: 120 (number)
            + `hourly_remaining`: 117 (number)

# Topic [/topics]

主题相关接口

## 获取最新主题列表 [GET /topics/latest.json]

+ Response 200 (application/json)

    + Attributes (array)
        + (object)
            + node
                + `avatar_large`: `//cdn.v2ex.com/navatar/38af/8613/176_large.png?m=1583743753`
                + name: car
                + `avatar_normal`: `//cdn.v2ex.com/navatar/38af/8613/176_normal.png?m=1583743753`
                + title: 汽车
                + url: `https://www.v2ex.com/go/car`
                + topics: 863 (number)
                + footer
                + header: 关于买车、开车的技术讨论
                + `title_alternative`: Car
                + `avatar_mini`: `//cdn.v2ex.com/navatar/38af/8613/176_mini.png?m=1583743753`
                + stars: 897 (number)
                + aliases (array)
                + root: false (boolean)
                + id: 176 (number)
                + `parent_node_name`
            + `member` - 发帖人信息
                + username: wellcheng
                + website (object, nullable)
                + github (object, nullable)
                + psn (object, nullable)
                + `avatar_normal`: `//cdn.v2ex.com/avatar/c072/a096/147096_mini.png?m=1506150991`
                + bio (object, nullable)
                + url: `https://www.v2ex.com/u/wellcheng`
                + tagline (object, nullable)
                + twitter (object, nullable)
                + created: 1447465468 (number)
                + `avatar_large`: `//cdn.v2ex.com/avatar/c072/a096/147096_mini.png?m=1506150991`
                + `avatar_mini`: `//cdn.v2ex.com/avatar/c072/a096/147096_mini.png?m=1506150991`
                + location (object, nullable)
                + btc (object, nullable)
                + id: 147096 (number)
            + `last_reply_by`
            + `last_touched`: 1584358122 (number)
            + title: 中了杭州油牌， 15W 预算怎么选
            + url: `https://www.v2ex.com/t/653358`
            + created: 1584358122 (number)
            + content: 本来打算先摇油牌，年底去了杭州 Model 3 上绿牌，毕竟心水 Model 3 很久了。 ...
            + `content_rendered`: `<p>本来打算先摇油牌，年底去了杭州 Model 3 上绿牌，毕竟心水 Model 3 很久了。</p> ...`
            + `last_modified`: 1584358122 (number)
            + replies: 0 (number)
            + id: 653358 (number)

## 获取热门主题列表 [GET /topics/hot.json]

+ Response 200 (application/json)

    + Attributes (array)
        + (object)
            + node
                + `avatar_large`: `//cdn.v2ex.com/navatar/c20a/d4d7/12_large.png?m=1582188154`
                + name: qna
                + `avatar_normal`: `//cdn.v2ex.com/navatar/c20a/d4d7/12_normal.png?m=1582188154`
                + title: 问与答
                + url: `https://www.v2ex.com/go/qna`
                + topics: 149962 (number)
                + footer
                + header: 一个更好的世界需要你持续地提出好问题。
                + `title_alternative`: Questions and Answers
                + `avatar_mini`: `//cdn.v2ex.com/navatar/c20a/d4d7/12_mini.png?m=1582188154`
                + stars: 2845 (number)
                + aliases (array)
                + root: false (boolean)
                + id: 12 (number)
                + `parent_node_name`: v2ex
            + `member`
                + username: pmyile
                + website (object, nullable)
                + github (object, nullable)
                + psn (object, nullable)
                + `avatar_normal`: //cdn.v2ex.com/gravatar/e3a335caac65caf6f45c66533148713a?s=24&d=retro
                + bio (object, nullable)
                + url: `https://www.v2ex.com/u/pmyile`
                + tagline (object, nullable)
                + twitter (object, nullable)
                + created: 1543832388 (number)
                + `avatar_large`: //cdn.v2ex.com/gravatar/e3a335caac65caf6f45c66533148713a?s=24&d=retro
                + `avatar_mini`: //cdn.v2ex.com/gravatar/e3a335caac65caf6f45c66533148713a?s=24&d=retro
                + location (object, nullable)
                + btc (object, nullable)
                + id: 367634 (number)
            + `last_reply_by`: syyy
            + `last_touched`: 1584358174 (number)
            + title: QQ 现在那么难用 目标用户是什么群体呢？ 是否已经迷失
            + url: `https://www.v2ex.com/t/653154`
            + created: 1584322968 (number)
            + content: 发现莫名其妙关注很多公众号的东西，都是腾讯旗下的各种垃圾功能，手动取关后发现稍不注意又会给你自动关注，还有 QQ 空间不再纯粹，稍不注意就是点进各种微视频乱七八糟的功能，老子就是想看看空间啊，，怎么整的像是来到了杂货铺似的。
            + `content_rendered`: `<p>发现莫名其妙关注很多公众号的东西，都是腾讯旗下的各种垃圾功能，手动取关后发现稍不注意又会给你自动关注，还有 QQ 空间不再纯粹，稍不注意就是点进各种微视频乱七八糟的功能，老子就是想看看空间啊，，怎么整的像是来到了杂货铺似的。</p> ...`
            + `last_modified`: 1584322968 (number)
            + replies: 154 (number)
            + id: 653154 (number)

## 获取指定主题信息 [GET /topics/show.json{?id,username,node_id,node_name}]

参数四选一。

+ Parameters
    + id: `1000` (number)

+ Response 200 (application/json)

    + Attributes (array)
        + (object)
            + node
                + `avatar_large`: `//cdn.v2ex.com/navatar/c4ca/4238/1_large.png?m=1494924246`
                + name: babel
                + `avatar_normal`: `//cdn.v2ex.com/navatar/c4ca/4238/1_normal.png?m=1494924246`
                + title: Project Babel
                + url: `https://www.v2ex.com/go/babel`
                + topics: 1122 (number)
                + footer: `V2EX 基于 Project Babel 驱动。Project Babel 是用 Python 语言写成的，运行于 Google App Engine 云计算平台上的社区软件。Project Babel 当前开发分支 2.5。最新版本可以从 <a href="http://github.com/livid/v2ex" target="_blank">GitHub</a> 获取。`
                + header: `Project Babel - 帮助你在云平台上搭建自己的社区`
                + `title_alternative`: Project Babel
                + `avatar_mini`: `//cdn.v2ex.com/navatar/c4ca/4238/1_mini.png?m=1494924246`
                + stars: 397 (number)
                + aliases (array)
                + root: false (boolean)
                + id: 1 (number)
                + `parent_node_name`: v2ex
            + `member`
                + username: Livid
                + website: `https://livid.v2ex.com/`
                + github
                + psn
                + `avatar_normal`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1583753654`
                + bio: Remember the bigger green
                + url: `https://www.v2ex.com/u/Livid`
                + tagline: Gravitated and spellbound
                + twitter
                + created: 1272203146 (number)
                + `avatar_large`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1583753654`
                + `avatar_mini`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1583753654`
                + location
                + btc
                + id: 1 (number)
            + `last_reply_by`: dimlau
            + `last_touched`: 1280285385 (number)
            + title: Google App Engine x MobileMe
            + url: `https://www.v2ex.com/t/1000`
            + created: 1280192329 (number) - 主题创建时间戳
            + content: 从现在开始，新上传到 V2EX 的头像将存储在 MobileMe iDisk 中。这是 V2EX 到目前为之所用到的第三个云。 ...
            + `content_rendered`: 从现在开始，新上传到 V2EX 的头像将存储在 MobileMe iDisk 中。这是 V2EX 到目前为之所用到的第三个云。 ...
            + `last_modified`: 1335004238 (number)
            + replies: 14 (number)
            + id: 1000 (number)

+ Request (application/json)

    + Parameters
        + username: `Livid` - 根据用户名取该用户所发表主题
        + node_id (object) - 根据节点 ID 取该节点下所有主题
        + node_name (object) - 根据节点名取该节点下所有主题

+ Response 200 (application/json)

    + Attributes (array)
        + (object)
            + node
                + `avatar_large`: `//cdn.v2ex.com/navatar/e00d/a03b/139_large.png?m=1584118213`
                + name: css
                + `avatar_normal`: `//cdn.v2ex.com/navatar/e00d/a03b/139_normal.png?m=1584118213`
                + title: CSS
                + url: `https://www.v2ex.com/go/css`
                + topics: 425 (number)
                + footer
                + header: Cascading Style Sheet，层叠样式表，网页外观设计的标准技术。
                + `title_alternative`: CSS
                + `avatar_mini`: `//cdn.v2ex.com/navatar/e00d/a03b/139_mini.png?m=1584118213`
                + stars: 603 (number)
                + aliases (array)
                + root: false (boolean)
                + id: 139 (number)
                + `parent_node_name`: programming
            + `member`
                + username: Livid
                + website: `https://livid.v2ex.com/`
                + github
                + psn
                + `avatar_normal`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1583753654`
                + bio: Remember the bigger green
                + url: `https://www.v2ex.com/u/Livid`
                + tagline: Gravitated and spellbound
                + twitter
                + created: 1272203146 (number)
                + `avatar_large`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1583753654`
                + `avatar_mini`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1583753654`
                + location
                + btc
                + id: 1 (number)
            + `last_reply_by`: cmdOptionKana
            + `last_touched`: 1584243137 (number)
            + title: CSS 语法中两个类之间的空格
            + url: `https://www.v2ex.com/t/652657`
            + created: 1584118153 (number)
            + content: 最近搞明白的一件事情，下面两种语法的区别： ...
            + `content_rendered`: `<p>最近搞明白的一件事情，下面两种语法的区别：</p> ...`
            + `last_modified`: 1584118153 (number)
            + replies: 58 (number)
            + id: 652657 (number)

# Replies [/replies]

主题回复相关接口

## 获取指定主题的所有回复列表 [GET /replies/show.json{?topic_id,page,page_size}]

+ Parameters
    + topic_id: `1` (number)
    + page: `1` (number) - 当前页数
    + page_size: `20` (number) - 每页条数

+ Response 200 (application/json)

    + Attributes (array)
        + (object)
            + `member`
                + username: Jay
                + website: `http://theboldapp.com`
                + github: yuanhao
                + psn
                + `avatar_normal`: `//cdn.v2ex.com/avatar/a87f/f679/4_mini.png?m=1424948183`
                + bio
                + url: `https://www.v2ex.com/u/Jay`
                + tagline: Engineer. Make things.
                + twitter: yuanhao
                + created: 1272207173 (number)
                + `avatar_large`: `//cdn.v2ex.com/avatar/a87f/f679/4_mini.png?m=1424948183`
                + `avatar_mini`: `//cdn.v2ex.com/avatar/a87f/f679/4_mini.png?m=1424948183`
                + location: Stuttgart
                + btc
                + id: 4 (number)
            + created: 1272207477 (number)
            + `topic_id`: 1 (number)
            + content: 很高兴看到 v2ex 又回来了，等了你半天发第一贴了，憋死我了。 ...
            + `content_rendered`: `很高兴看到 v2ex 又回来了，等了你半天发第一贴了，憋死我了。<br /><br />nice work~`
            + `last_modified`: 1335092176 (number) - 最后编辑时间戳
            + `member_id`: 4 (number)
            + id: 1 (number)

# Members [/members]

用户相关接口

## 获取指定主题的所有回复列表 [GET /members/show.json{?username}]

+ Parameters
    + username: `Livid`

+ Response 200 (application/json)

    + Attributes
        + username: Livid
        + website: `https://livid.v2ex.com/`
        + github
        + psn
        + `avatar_normal`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1583753654` - 头像 URL
        + bio: Remember the bigger green
        + url: `https://www.v2ex.com/u/Livid`
        + tagline: Gravitated and spellbound
        + twitter
        + created: 1272203146 (number)
        + status: found
        + `avatar_large`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1583753654`
        + `avatar_mini`: `//cdn.v2ex.com/avatar/c4ca/4238/1_mini.png?m=1583753654`
        + location
        + btc
        + id: 1 (number)

